server {
    listen 80;
    server_name vizhnmag.ru;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name vizhnmag.ru;

    root /var/www/public;
    index index.php index.html;

    ssl_certificate /etc/letsencrypt/live/vizhnmag.ru/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/vizhnmag.ru/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass app:9000;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }

    location ~ /\.ht {
        deny all;
    }
}
